Issue #4: overdoing backups could lead to backup loss
Do not do a backup in interval INT if the oldest INT-1 is not at
least threshold(INT) seconds newer than the newer snapshot in INT
interval, where threshold(INT) is the the minimum time disance
between 2 backups in the INT interval.

A new extra condition intrdoduced for backing up INT interval:

 ts(oldest(INT-1)) - ts(newest(INT)) >= threshold(INT)

This should ensure backups int INT interval are at least
threshold(INT) seconds apart from each other.

This new condition fixes #4.

Without this condition previously backups from the INT-1 interval
were promoted indiscriminantly into the INT interval.

This was leading to situations like the one below were weekly
backups would not be at least 1 week apart from each other, or
monthly backups not being at least 30 days from eachother:

drwxr-xr-x 3 eddy eddy 4096 mar  3 21:27 hourly.0
drwxr-xr-x 3 eddy eddy 4096 mar  2 20:38 hourly.1
drwxr-xr-x 3 eddy eddy 4096 mar  1 15:09 daily.0
drwxr-xr-x 3 eddy eddy 4096 feb 27 21:31 daily.1
drwxr-xr-x 3 eddy eddy 4096 feb 26 23:12 daily.2
drwxr-xr-x 3 eddy eddy 4096 feb 25 20:20 daily.3
drwxr-xr-x 3 eddy eddy 4096 feb 25 00:32 daily.4
drwxr-xr-x 3 eddy eddy 4096 feb 24 00:15 daily.5
drwxr-xr-x 3 eddy eddy 4096 feb 15 22:26 weekly.0
drwxr-xr-x 3 eddy eddy 4096 feb 15 22:24 weekly.1
drwxr-xr-x 3 eddy eddy 4096 feb 13 12:12 weekly.2
drwxr-xr-x 3 eddy eddy 4096 feb 13 01:30 weekly.3
drwxr-xr-x 3 eddy eddy 4096 feb  9 22:32 weekly.4
drwxr-xr-x 3 eddy eddy 4096 feb  9 14:21 monthly.0
drwxr-xr-x 3 eddy eddy 4096 ian 26 02:27 monthly.1
drwxr-xr-x 3 eddy eddy 4096 ian 25 22:02 monthly.2
drwxr-xr-x 3 eddy eddy 4096 ian 24 16:50 monthly.3

Note the monthly backups which are actually 1 day apart from
each other (1-2-3 monthly snapshots) and the weekly backups which
are hours apart from each other (see the 0-1 and 2-3 pairs in the
weekly interval).

Signed-off-by: Eddy Petrișor <eddy.petrisor@gmail.com>

diff --git a/occasional_rsnapshot b/occasional_rsnapshot
--- a/occasional_rsnapshot
+++ b/occasional_rsnapshot
@@ -94,12 +94,35 @@ can_backup_interval ()
 	fi
 	debug "Configured retain count for '$pint' is '$prev_retain_count'."
 
-	must_exist_dir="${SROOT}${pint}.$(( ${prev_retain_count} - 1 ))"
+	pint_max_index=$(( ${prev_retain_count} - 1 ))
+	must_exist_dir="${SROOT}${pint}.$pint_max_index"
 	# if the maximum from the smaller interval exists, then we can
 	# backup this interval, otherwise, it makes no sense since we might
 	# lose info
 	if [ -d "${must_exist_dir}" ]; then
-		debug "Directory '$must_exist_dir' exists, so '$interval' can be backed up, too."
+		debug "Directory '$must_exist_dir' exists, so '$interval' could be backed up, too."
+		newest_snap_dir=${SROOT}${interval}.0
+		if [ -d "${newest_snap_dir}" ]; then
+			local ts_pint_dir="$(get_file_timestamps $pint $pint_max_index)"
+			if [ -z "$ts_pint_dir" ]; then
+				echo "Internal error: could not get timestamp of existing directory $must_exist_dir (oldest in $pint interval). Quitting."
+				exit 2
+			fi
+			local ts_int_dir="$(get_file_timestamps $interval 0)"
+			if [ -z "$ts_int_dir" ]; then
+				echo "Internal error: could not get timestamp of existing directory $newest_snap_dir (newest in $interval interval). Quitting."
+				exit 2
+			fi
+			tsdiff=$(( ${ts_pint_dir} - ${ts_int_dir} ))
+			if [ $tsdiff -ge ${min_int[$interval]} ]; then
+				debug "Oldest $pint snapshot is $tsdiff away from newest $interval snapshot and more than ${min_int[$interval]}s old. Will backup '$interval'."
+				return 0
+			else
+				debug "Not enough time passed since oldest $pint snapshot was done to justify a $interval backup. Skipping."
+				return 1
+			fi
+		fi
+		debug "No previous snapshot for interval '$interval', so backup will be done."
 		return 0
 	else
 		debug "Directory '$must_exist_dir' is NOT present, so trying to backup the '$interval' interval doesn't make sense."
